name: Deploy on VPS
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST}}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                script: |
                      cd /var/www/tradx-web
                      git stash
                      git pull origin main
                      npm i --legacy-peer-deps
                      npm run build
